version: '3.8'

services:
  route-optimizer:
    build: .
    container_name: route-optimizer
    volumes:
      - ./API_token_cloud_google.txt:/app/API_token_cloud_google.txt
    ports:
      - "8080:8080"
    restart: always
